일기:
    - {fileName: '20210525'}
    - {fileName: '20210622'}
    - {fileName: '20211108'}
    - {fileName: '20211115'}
    - {fileName: '20220413'}
    - {fileName: '20230814'}
my_project:
    - {fileName: about_neoarc_macro_js}
    - {fileName: about_super_fanmade_mario_bros}
macro:
    - {fileName: about_neoarc_macro_js}
자동화:
    - {fileName: about_neoarc_macro_js}
    - {fileName: power_automate_desktop}
매크로:
    - {fileName: about_neoarc_macro_js}
sfmb:
    - {fileName: about_super_fanmade_mario_bros}
    - {fileName: sfmb_betatest}
    - {fileName: sfmb_betatest_community_moderator}
    - {fileName: sfmb_contribute_sprite}
    - {fileName: sfmb_contribution_agreement}
    - {fileName: sfmb_exp_and_coin_table}
    - {fileName: sfmb_frequently_asked_question}
    - {fileName: sfmb_how_to_make_parallax_background}
    - {fileName: sfmb_how_to_setup_pro_controller}
    - {fileName: sfmb_how_to_use_sprite_editor}
    - {fileName: sfmb_level_difficulty}
    - {fileName: sfmb_mapeditor_guide}
    - {fileName: sfmb_privacy_and_security}
    - {fileName: sfmb_privacy_policy}
    - {fileName: sfmb_roadmap}
    - {fileName: sfmb_sprite_index}
    - {fileName: sfmb_stage_rating}
    - {fileName: sfmb_trouble_shooting}
    - {fileName: sfmb_tutorial}
    - {fileName: sfmb_version_history}
    - {fileName: sfmb_why_do_you_like_this_game}
게임:
    - {fileName: games_i_have_enjoyed}
악성코드:
    - {fileName: i_found_unknown_malware}
nodejs:
    - {fileName: make_nodejs_server_on_oracle_cloud}
기부하기:
    - {fileName: my_wiki_donation}
donation:
    - {fileName: my_wiki_donation}
google_translator:
    - {fileName: my_wiki_google_translator}
gadget:
    - {fileName: my_wiki_google_translator}
wiki:
    - {fileName: my_wiki_todolist}
    - {fileName: wiki_i_have_tried}
    - {fileName: wiki_on_github_io}
johngrib_wiki:
    - {fileName: my_wiki_todolist}
utility:
    - {fileName: power_automate_desktop}
automation:
    - {fileName: power_automate_desktop}
유틸리티:
    - {fileName: power_automate_desktop}
sfmb-sprite:
    - {fileName: sfmb_sprite_index}
잡담:
    - {fileName: sleepy_moment}
idle_talk:
    - {fileName: sleepy_moment}
노래:
    - {fileName: useless_memory_i_forget_again_and_again}
음악:
    - {fileName: useless_memory_i_forget_again_and_again}
github.io:
    - {fileName: wiki_on_github_io}
vimwiki:
    - {fileName: wiki_on_github_io}
jekyll:
    - {fileName: wiki_on_github_io}
